# Generated by Django 2.0.4 on 2018-09-06 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 14, 48, 5, 495318, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
